# Ayudantía 11: Tópicos Avanzados 🔮
Por sus queridos ayudantes de catedra:

* Diego Toledo
* Francisca Cares
* Carlos Martel
* Agustín Becker
* Julio Huerta

# Índice

- [Introducción](#introduccion)
- [Uso de Regex](#regex-(regular-expresions))
- [Representación de Grafos](#grafos)
- [Operaciones con NumPy](#numpy)
- [Análisis de Datos con Pandas](#pandas)

## Introduccion

Python es un lenguaje que destaca por su versatilidad y potencia, capaz de abordar desde tareas simples hasta problemas complejos en ciencia de datos, análisis de información y estructuras algorítmicas avanzadas. En esta ayudantía exploraremos el verdadero potencial de Python a través de algunas de sus librerías más poderosas: **Regex**, para manipulación avanzada de texto y patrones; **representación de grafos**, una herramienta clave para modelar relaciones y estructuras en distintos ámbitos; **Pandas**, que nos permite gestionar y analizar grandes volúmenes de datos de manera flexible; y finalmente, **NumPy**, esencial para cálculos numéricos eficientes. Con estos temas, buscaremos no solo profundizar en su funcionamiento, sino también demostrar cómo Python se convierte en una herramienta util, e imprescindible para el desarrollo de soluciones eficientes y escalables.

# Regex (Regular Expresions)

Hasta ahora cada vez que necesitamos procesar la información contenida en *strings* lo hemos hecho mediante los mismos métodos que la clase `str` nos provee. Esto es fácil cuando el texto que analizamos es relativamente simple.

Que pasa si le pedimos algo mas complejo? 

Existe una forma mas eficiente y poderosa que consiste en describir patrones de busqueda. REGEX!!!

Las expresiones regulares permiten especificar un conjunto de *strings* que hacen *match* con ella. Cada carácter en una expresión regular hace *match* exactamente con el carácter correspondiente de un *string*. Por ejemplo, la expresión regular `abcde` permite hacer *match* únicamente con el *string* `abcde`. Esto no parece muy poderoso pues hemos especificado exactamente el mismo *string* que queríamos reconocer. Sin embargo, las expresiones regulares utilizan algunos caracteres especiales, denominados **meta-caracteres** para especificar patrones más generales.

Los principales meta-caracteres son: ```. ^ $ * + ? { } [ ] \ | ( )```, y su significado es el siguiente:

In [6]:
import re

def test(pattern, test_str):
    if re.search(pattern, test_str):
        print(f"✅ '{test_str}' MATCHES '{pattern}'")
    else:
        print(f"❌ '{test_str}' does NOT match '{pattern}'")

# 1. . (punto) - cualquier carácter excepto \n
print("\n1. . (punto)")
test(r".", "a")     # ✅
test(r".", "\n")    # ❌

# 2. ^ - inicio de línea
print("\n2. ^ (inicio de línea)")
test(r"^Hello", "Hello world")   # ✅
test(r"^Hello", "world Hello")   # ❌

# 3. $ - fin de línea
print("\n3. $ (fin de línea)")
test(r"world$", "Hello world")   # ✅
test(r"world$", "world Hello")   # ❌

# 4. * - 0 o más repeticiones
print("\n4. * (0 o más)")
test(r"ab*c", "ac")      # ✅
test(r"ab*c", "abbc")    # ✅
test(r"ab*c", "adc")     # ❌

# 5. + - 1 o más repeticiones
print("\n5. + (1 o más)")
test(r"ab+c", "ac")      # ❌
test(r"ab+c", "abc")     # ✅
test(r"ab+c", "abbbc")   # ✅

# 6. ? - 0 o 1 repetición
print("\n6. ? (0 o 1)")
test(r"ab?c", "ac")      # ✅
test(r"ab?c", "abc")     # ✅
test(r"ab?c", "abbc")    # ❌

# 7. { } - número específico de repeticiones
print("\n7. {n} (exactamente n repeticiones)")
test(r"a{3}", "aaa")     # ✅
test(r"a{3}", "aa")      # ❌

print("\n7b. {n,m} (entre n y m repeticiones)")
test(r"a{2,4}", "aa")    # ✅
test(r"a{2,4}", "aaaa")  # ✅
test(r"a{2,4}", "a")     # ❌

# 8. [ ] - conjunto de caracteres
print("\n8. [ ] (conjunto de caracteres)")
test(r"[aeiou]", "e")    # ✅
test(r"[aeiou]", "z")    # ❌

# 9. \ - escape de metacaracteres
print("\n9. \\ (escape de metacaracteres)")
test(r"\.", ".")        # ✅ (match con un punto literal)
test(r"\.", "a")        # ❌

# 10. | - alternancia (OR)
print("\n10. | (alternancia)")
test(r"cat|dog", "cat")  # ✅
test(r"cat|dog", "dog")  # ✅
test(r"cat|dog", "bird") # ❌

# 11. ( ) - grupos
print("\n11. ( ) (grupos)")
test(r"(abc)+", "abcabc")  # ✅
test(r"(abc)+", "abc")     # ✅
test(r"(abc)+", "ab")      # ❌

# 12. ^ - inicio de línea
print("\n1. ^ (inicio de línea)")
test(r"^Hello", "Hello world")   # ✅
test(r"^Hello", "Say Hello")     # ❌

# 13. $ - fin de línea
print("\n2. $ (fin de línea)")
test(r"world$", "Hello world")   # ✅
test(r"world$", "world Hello")   # ❌

1. . (punto)
✅ 'a' MATCHES '.'
❌ '
' does NOT match '.'

2. ^ (inicio de línea)
✅ 'Hello world' MATCHES '^Hello'
❌ 'world Hello' does NOT match '^Hello'

3. $ (fin de línea)
✅ 'Hello world' MATCHES 'world$'
❌ 'world Hello' does NOT match 'world$'

4. * (0 o más)
✅ 'ac' MATCHES 'ab*c'
✅ 'abbc' MATCHES 'ab*c'
❌ 'adc' does NOT match 'ab*c'

5. + (1 o más)
❌ 'ac' does NOT match 'ab+c'
✅ 'abc' MATCHES 'ab+c'
✅ 'abbbc' MATCHES 'ab+c'

6. ? (0 o 1)
✅ 'ac' MATCHES 'ab?c'
✅ 'abc' MATCHES 'ab?c'
❌ 'abbc' does NOT match 'ab?c'

7. {n} (exactamente n repeticiones)
✅ 'aaa' MATCHES 'a{3}'
❌ 'aa' does NOT match 'a{3}'

7b. {n,m} (entre n y m repeticiones)
✅ 'aa' MATCHES 'a{2,4}'
✅ 'aaaa' MATCHES 'a{2,4}'
❌ 'a' does NOT match 'a{2,4}'

8. [ ] (conjunto de caracteres)
✅ 'e' MATCHES '[aeiou]'
❌ 'z' does NOT match '[aeiou]'

9. \ (escape de metacaracteres)
✅ '.' MATCHES '\.'
❌ 'a' does NOT match '\.'

10. | (alternancia)
✅ 'cat' MATCHES 'cat|dog'
✅ 'dog' MATCHES 'cat|dog'
❌ 'bird' does NOT match 'cat|dog'

11. ( ) (grupos)
✅ 'abcabc' MATCHES '(abc)+'
✅ 'abc' MATCHES '(abc)+'
❌ 'ab' does NOT match '(abc)+'

1. ^ (inicio de línea)
✅ 'Hello world' MATCHES '^Hello'
❌ 'Say Hello' does NOT match '^Hello'

2. $ (fin de línea)
✅ 'Hello world' MATCHES 'world$'
❌ 'world Hello' does NOT match 'world$'

Ademas existen clases de caracteres previamente definidas. Estas son:

In [7]:
import re

def test(pattern, test_str):
    if re.search(pattern, test_str):
        print(f"✅ '{test_str}' MATCHES '{pattern}'")
    else:
        print(f"❌ '{test_str}' does NOT match '{pattern}'")

# 1. \d - dígito
print("\n1. \\d (dígito)")
test(r"\d", "5")    # ✅
test(r"\d", "a")    # ❌

# 2. \D - no dígito
print("\n2. \\D (no dígito)")
test(r"\D", "a")    # ✅
test(r"\D", "5")    # ❌

# 3. \s - espacio en blanco
print("\n3. \\s (espacio en blanco)")
test(r"\s", " ")    # ✅
test(r"\s", "a")    # ❌

# 4. \S - no espacio en blanco
print("\n4. \\S (no espacio en blanco)")
test(r"\S", "a")    # ✅
test(r"\S", " ")    # ❌

# 5. \w - "word character" (letra, número, o _)
print("\n5. \\w (word character)")
test(r"\w", "a")    # ✅
test(r"\w", "5")    # ✅
test(r"\w", "_")    # ✅
test(r"\w", "#")    # ❌

# 6. \W - no "word character"
print("\n6. \\W (no word character)")
test(r"\W", "#")    # ✅
test(r"\W", "a")    # ❌

1. \d (dígito)
✅ '5' MATCHES '\d'
❌ 'a' does NOT match '\d'

2. \D (no dígito)
✅ 'a' MATCHES '\D'
❌ '5' does NOT match '\D'

3. \s (espacio en blanco)
✅ ' ' MATCHES '\s'
❌ 'a' does NOT match '\s'

4. \S (no espacio en blanco)
✅ 'a' MATCHES '\S'
❌ ' ' does NOT match '\S'

5. \w (word character)
✅ 'a' MATCHES '\w'
✅ '5' MATCHES '\w'
✅ '_' MATCHES '\w'
❌ '#' does NOT match '\w'

6. \W (no word character)
✅ '#' MATCHES '\W'
❌ 'a' does NOT match '\W'

Dentro del modulo re de python tenemos distintas funciones, tales como

- [`re.match()`](https://docs.python.org/es/3/library/re.html#re.match) verifica si un *substring* cumple con la expresión regular a partir del inicio del *string*.
- [`re.fullmatch()`](https://docs.python.org/es/3/library/re.html#re.fullmatch) verifica si el *string* completo cumple con la expresión regular
- [`re.search()`](https://docs.python.org/es/3/library/re.html#re.search) verifica si algún *substring* cumple con la expresión regular.
- [`re.sub()`](https://docs.python.org/es/3/library/re.html#re.sub) permite reemplazar un patrón por otra secuencia de caracteres en un *string*.
- [`re.split()`](https://docs.python.org/es/3/library/re.html#re.split) permite separar un *string* de acuerdo a un patrón.

In [8]:
import re

# 1. re.match() - solo al inicio
print("\n1. re.match()")
pattern = r"Hello"
print("✅", re.match(pattern, "Hello world"))   # match
print("❌", re.match(pattern, "Say Hello"))     # no match

# 2. re.fullmatch() - todo el string debe coincidir
print("\n2. re.fullmatch()")
pattern = r"\d{3}"  # exactamente 3 dígitos
print("✅", re.fullmatch(pattern, "123"))       # match
print("❌", re.fullmatch(pattern, "1234"))      # no match
print("❌", re.fullmatch(pattern, "12"))        # no match

# 3. re.search() - primera coincidencia en cualquier parte
print("\n3. re.search()")
pattern = r"cat"
print("✅", re.search(pattern, "the black cat"))    # match
print("❌", re.search(pattern, "the black dog"))    # no match

# 4. re.sub() - sustitución
print("\n4. re.sub()")
pattern = r"\d+"  # uno o más dígitos
text = "My phone number is 12345."
result = re.sub(pattern, "XXXXX", text)
print(f"Original: {text}")
print(f"Substituido: {result}")

# 5. re.split() - dividir por patrón
print("\n5. re.split()")
pattern = r"\s+"  # uno o más espacios en blanco
text = "split   this text   into words"
result = re.split(pattern, text)
print(f"Original: {text}")
print(f"Resultado: {result}")

1. re.match()
✅ <re.Match object; span=(0, 5), match='Hello'>
❌ None

2. re.fullmatch()
✅ <re.Match object; span=(0, 3), match='123'>
❌ None
❌ None

3. re.search()
✅ <re.Match object; span=(10, 13), match='cat'>
❌ None

4. re.sub()
Original: My phone number is 12345.
Substituido: My phone number is XXXXX.

5. re.split()
Original: split   this text   into words
Resultado: ['split', 'this', 'text', 'into', 'words']



### Ejercicio: DCContraseña: 


La orden magica de los programadores (DCC) ha creado un portal magico que permite acceder a la biblioteca de sabiduria eterna. Pero para entrar, cada aprendiz debe crear una contraseña segura que supere los filtros del gran Guardián Regexius.

Regexius es muy estricto, y exige que toda contraseña cumpla con los siguientes requisitos:

- ✨ Al menos 8 caracteres
- 🏰 Al menos una letra mayúscula
- 📜 Al menos una letra minúscula
- 🔢 Al menos un número
- 🗡️ Al menos un carácter especial (!@#$%^&*()_+-=[]{};':"\|,.<>/?)

Tu mision como aprendiz es programar la funcion *validar_contraseña(password)* que determina si la contraseña será aceptada por Regexius. Si la contraseña no es segura, Regexius te bloqueara la entrada.

In [9]:
import re

def validar_contrasena(password):
    errores = []
    
    if len(password) < 8:
        errores.append("❌ La contraseña debe tener al menos 8 caracteres.")

    if not re.search(r"[A-Z]", password):
        errores.append("❌ Falta al menos una letra mayúscula.")

    if not re.search(r"[a-z]", password):
        errores.append("❌ Falta al menos una letra minúscula.")

    if not re.search(r"[0-9]", password):
        errores.append("❌ Falta al menos un número.")

    if not re.search(r"[!@#$%^&*()_+\-=\[\]{};':\"\\|,.<>\/?]", password):
        errores.append("❌ Falta al menos un carácter especial.")
        
    
    if not errores:
        return "✅ ¡Contraseña válida! El portal se abre. 🏰\n" 
    else:
        return "\n".join(errores) + '\n'

# Ejemplo de uso:
print(validar_contrasena("Abcdef123!"))
print(validar_contrasena("abcdefghi"))
print(validar_contrasena("Abcdefghi"))

✅ ¡Contraseña válida! El portal se abre. 🏰

❌ Falta al menos una letra mayúscula.
❌ Falta al menos un número.
❌ Falta al menos un carácter especial.

❌ Falta al menos un número.
❌ Falta al menos un carácter especial.

¿Porque no podemos utilizar un solo patron para verificar la contraseña?

In [10]:
patron = r"^[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':\"\\|,.<>\/?]{8,}$"

Cual es el problema con nuestro patron?
<details>
<summary> Ver respuesta </summary>

El patron no garantiza que se utilize cada uno de los requisitos de nuestra contraseña, sino que lo que hace es aceptar todas las contraseñas que utilizen al menos uno de los caracteres especificados. El patron puede aceptar contraseñas solo con minusculas o solo con numeros, etc.
</details>

# Grafos

Un grafo es un conjunto no vacio compuesto por **nodos** y **relaciones** entre estos. Formalmente se les conoce como **Vertices** y **Aristas** a cada uno respectivamente.

Un grafo puede ser **dirijido** o **no dirigido**:
- Dirigido: Las relaciones entre nodos tienen una orientacion (direccion).
- No dirijido: Las relaciones son simetricas (No importa la direccion de la relacion)

### ¿Como represento un grafo?

Existen muchas formas para hacerlo, en python veremos:

- Representacion Nodal: Creamos la clase nodo que contiene el valor del nodo y sus vecinos. Ademas de un metodo para agregar nodos.

In [11]:
# Nodo de un grafo
class Nodo:

    # Un nodo está compuesto por el valor que almacena y una lista de sus nodos vecinos
    def __init__(self, valor):
        self.valor = valor
        self.vecinos = []

    def agregar_vecino(self, nodo):
        self.vecinos.append(nodo)

    def __repr__(self):
        texto = f"[{self.valor}]"
        if len(self.vecinos) > 0:
            textos_vecinos = [f"[{vecino.valor}]" for vecino in self.vecinos]
            texto += " -> " + ", ".join(textos_vecinos)
        return texto

In [12]:
nodo_1 = Nodo(1)
nodo_2 = Nodo(2)
nodo_3 = Nodo(3)
nodo_4 = Nodo(4)
nodo_5 = Nodo(5)

nodo_1.agregar_vecino(nodo_2)
nodo_2.agregar_vecino(nodo_3) 
nodo_3.agregar_vecino(nodo_2) 
nodo_3.agregar_vecino(nodo_4)
nodo_3.agregar_vecino(nodo_5) 
nodo_4.agregar_vecino(nodo_5)

print(nodo_1)
print(nodo_2)
print(nodo_3)
print(nodo_4)
print(nodo_5)

[1] -> [2]
[2] -> [3]
[3] -> [2], [4], [5]
[4] -> [5]
[5]

- Listas de Adyacencia: Todos los vertices se guardan en una estructura, ademas se guarda una lista de los vertices a los que esta relacionado.

In [13]:
# Aquí usamos diccionarios con llave: int y valor: list porque ofrece más facilidad de búsqueda.
# Cada llave del diccionario es el valor de un vértice, y el valor asociado es la lista de vértices con conexión.

grafo_no_dirigido = {
    1: [2], 
    2: [1, 3], 
    3: [2, 4, 5], 
    4: [3, 5], 
    5: [3, 4]
}

grafo_dirigido = {
    1: [2], 
    2: [3], 
    3: [2, 4, 5], 
    4: [5], 
    5: []
}

In [14]:
# Podemos obtener los vértices del grafo como las llaves del diccionario
print("Lista de vértices:", list(grafo_no_dirigido.keys()))

# ¿Quiénes son los vecinos del vértice 3 en el grafo no dirigido?
print("Vecinos del vértices 3:", grafo_no_dirigido[3])

Lista de vértices: [1, 2, 3, 4, 5]
Vecinos del vértices 3: [2, 4, 5]

- Matriz de Adyacencia: Son matrices cuadradas donde las filas representan los vertices de origen y las columnas los vertices de llegada. Cada celda contiene un 0 o un 1. En caso de contener un 1, quiere decir que el nodo de la fila conecta con el nodo de la columna. En caso de un 0, no hay conexion.

In [ ]:
grafo_no_dirigido = [[0, 1, 0, 0, 0], 
                     [1, 0, 1, 0, 0],
                     [0, 1, 0, 1, 1], 
                     [0, 0, 1, 0, 1], 
                     [0, 0, 1, 1, 0]]

grafo_dirigido    = [[0, 1, 0, 0, 0], 
                     [0, 0, 1, 0, 0], 
                     [0, 1, 0, 1, 1], 
                     [0, 0, 0, 0, 1], 
                     [0, 0, 0, 0, 0]]

print("\nGrafo no dirigido:")
print('n  1  2  3  4  5')
for i, fila in enumerate(grafo_no_dirigido):
    print(f'{i+1} {fila}')

print("\nGrafo dirigido:")
print('n  1  2  3  4  5')
for i, fila in enumerate(grafo_dirigido):
    print(f'{i+1} {fila}')

Grafo no dirigido:
n  1  2  3  4  5
1 [0, 1, 0, 0, 0]
2 [1, 0, 1, 0, 0]
3 [0, 1, 0, 1, 1]
4 [0, 0, 1, 0, 1]
5 [0, 0, 1, 1, 0]

Grafo dirigido:
n  1  2  3  4  5
1 [0, 1, 0, 0, 0]
2 [0, 0, 1, 0, 0]
3 [0, 1, 0, 1, 1]
4 [0, 0, 0, 0, 1]
5 [0, 0, 0, 0, 0]

### Ejercicio: Explorando el Bosque Encantado

En el reino de Graphlandia, los magos han creado un gran bosque encantado.
El bosque está formado por varios claro mágicos conectados por senderos.

El aprendiz de mago Arin se ha perdido en el bosque. Tú eres el encargado de ayudarle a encontrar el camino desde el claro de inicio hasta un claro objetivo.

El bosque puede representarse como un grafo no dirigido, donde:
- Cada claro es un nodo
- Cada sendero es una arista

El rey te pide:

✅ Representar el bosque como una lista de adyacencia

✅ Implementar una función para encontrar un camino desde el claro de inicio hasta el claro objetivo

✅ Mostrar el camino encontrado (si existe)

##### Datos del bosque:

Los claros y senderos son:
- Claros: A, B, C, D, E, F
- Senderos: 
    - A - B
    - A - C
    - B - D
    - C - E
    - D - F
    - E - f

In [16]:
# Representación como lista de adyacencia
bosque = {
    'A': ['B', 'C'],
    'B': ['A', 'D'],
    'C': ['A', 'E'],
    'D': ['B', 'F'],
    'E': ['C', 'F'],
    'F': ['D', 'E']
}

# Búsqueda en profundidad (DFS) para encontrar un camino
def dfs_bosque(bosque, inicio, objetivo, visitados=None, camino=None):
    if visitados is None:
        visitados = set()
    if camino is None:
        camino = []

    visitados.add(inicio)
    camino.append(inicio)

    if inicio == objetivo:
        return camino

    for vecino in bosque[inicio]:
        if vecino not in visitados:
            resultado = dfs_bosque(bosque, vecino, objetivo, visitados, camino)
            if resultado is not None:
                return resultado

    camino.pop()
    return None

# Ejemplo de uso
inicio = 'A'
objetivo = 'F'
camino = dfs_bosque(bosque, inicio, objetivo)

if camino:
    print(f"\n🧭 El camino del claro {inicio} al claro {objetivo} es: {' -> '.join(camino)}")
else:
    print(f"\n⚠️ No hay camino del claro {inicio} al claro {objetivo}.")

🧭 El camino del claro A al claro F es: A -> B -> D -> F

## Numpy y Pandas

### Numpy

Numpy es una librería de Python ampliamente utilizada para realizar operaciones numéricas de forma eficiente. Su principal característica es el uso de arreglos (arrays) que ocupan bloques de memoria contiguos, lo que permite realizar operaciones vectorizadas y matriciales de manera rápida y optimizada.

A continuación veremos distintas funcionalidades:

In [2]:
import numpy as np
import codigos as cnp

tamano = 10000000
lista_a = list(range(tamano))
lista_b = list(range(tamano))

array_a = np.array(lista_a)
array_b = np.array(lista_b)

print("Comparación de tiempo entre listas y arrays de numpy")

# Suma de listas y arrays
print("Tiempo suma de listas:", cnp.suma_de_listas(lista_a, lista_b))
print("Tiempo suma de arrays:", cnp.suma_de_arrays(array_a, array_b))

# Promedio de listas y arrays
print("Tiempo promedio de lista:", cnp.promedio_de_lista(lista_a))
print("Tiempo promedio de array:", cnp.promedio_de_array(array_a))

# Obtener elementos mayores a un valor en listas y arrays
valor = 500000
print("Tiempo obtener elementos mayores en lista:", cnp.obtener_elementos_mayores_a_lista(lista_a, valor))
print("Tiempo obtener elementos mayores en array:", cnp.obtener_elementos_mayores_a_array(array_a, valor))

Comparación de tiempo entre listas y arrays de numpy
Tiempo suma de listas: 1.0076169967651367
Tiempo suma de arrays: 0.03861832618713379
Tiempo promedio de lista: 0.33984899520874023
Tiempo promedio de array: 0.016216278076171875
Tiempo obtener elementos mayores en lista: 0.6473815441131592
Tiempo obtener elementos mayores en array: 0.04817390441894531

### Pandas

Pandas es una librería de Python construida sobre Numpy que permite trabajar con estructuras de datos más complejas, como Series (unidimensionales) y DataFrames (bidimensionales).
Los DataFrames son estructuras similares a hojas de cálculo o tablas de bases de datos, y son la forma más común de trabajar con datos en Pandas. Permiten almacenar información en formato tabular y realizar operaciones sobre los datos de forma eficiente y sencilla.

In [5]:
import pandas as pd

# Cada llave del diccionario corresponde a una columna
# mientras que cada valor de la llave es una lista que contiene la fila

datos_mascotas = {
    'Nombre': ['Bobby', 'Luna', 'Max', 'Molly', 'Rocky'],
    'Raza': ['Labrador', 'Bulldog Francés', 'Pastor Alemán', 'Poodle', 'Golden Retriever'],
    'Año de Nacimiento': [2018, 2020, 2017, 2019, 2016],
    'Vacunación': ['Sí', 'No', 'Sí', 'Sí', 'No'],
    'Género': ['Macho', 'Hembra', 'Macho', 'Hembra', 'Macho']
}

df_mascotas = pd.DataFrame(datos_mascotas)
df_mascotas

  Nombre              Raza  Año de Nacimiento Vacunación  Género
0  Bobby          Labrador               2018         Sí   Macho
1   Luna   Bulldog Francés               2020         No  Hembra
2    Max     Pastor Alemán               2017         Sí   Macho
3  Molly            Poodle               2019         Sí  Hembra
4  Rocky  Golden Retriever               2016         No   Macho

In [6]:
# Podemos acceder a la información de la tabla
df_mascotas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nombre             5 non-null      object
 1   Raza               5 non-null      object
 2   Año de Nacimiento  5 non-null      int64
 3   Vacunación         5 non-null      object
 4   Género             5 non-null      object
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes

In [13]:
# Podemos acceder a columnas específicas de una tabla

mascotas_vacunadas = df_mascotas[df_mascotas['Vacunación'] == 'Sí']
mascotas_vacunadas

  Nombre           Raza  Año de Nacimiento Vacunación  Género
0  Bobby       Labrador               2018         Sí   Macho
2    Max  Pastor Alemán               2017         Sí   Macho
3  Molly         Poodle               2019         Sí  Hembra

In [14]:
# Podemos cargar directamente un archivo csv
df = pd.read_csv('datos.csv')
df

,rank,title,description,genre,rating,year
0,18,Spider-Man: Across the Spider-Verse,"Miles Morales catapults across the Multiverse,...",Animation;Action;Adventure,8.7,2023
1,32,Oppenheimer,"The story of American scientist, J. Robert Opp...",Biography;Drama;History,8.6,2023
2,77,Joker,A mentally troubled stand-up comedian embarks ...,Crime;Drama;Thriller,8.4,2019
3,76,Avengers: Endgame,After the devastating events of Avengers: Infi...,Action;Adventure;Drama,8.4,2019
4,37,Parasite,Greed and class discrimination threaten the ne...,Drama;Thriller,8.5,2019
...,...,...,...,...,...,...
95,99,Citizen Kane,Following the death of publishing tycoon Charl...,Drama;Mystery,8.3,1941
96,65,The Great Dictator,Dictator Adenoid Hynkel tries to expand his em...,Comedy;Drama;War,8.4,1940
97,49,Modern Times,The Tramp struggles to live in modern industri...,Comedy;Drama;Romance,8.5,1936
98,54,City Lights,"With the aid of a wealthy erratic tippler, a d...",Comedy;Drama;Romance,8.5,1931
99,100,M,When the police in a German city are unable to...,Crime;Mystery;Thriller,8.3,1931

In [15]:
# Ya que "genre" son múltiples géneros separados por ";", los separamos en listas
df['genre'] = df['genre'].str.split(';')
# Esto crea una fila duplicada por cada género en la lista
df_exploded = df.explode('genre')

# Obtenemos el promedio de rating por género
ratings_by_genre = df_exploded.groupby('genre')['rating'].mean()
print(ratings_by_genre)

genre
Action       8.573913
Adventure    8.514815
Animation    8.436364
Biography    8.537500
Comedy       8.425000
Crime        8.615000
Drama        8.545714
Family       8.533333
Fantasy      8.533333
Film-Noir    8.400000
History      8.633333
Horror       8.466667
Music        8.466667
Musical      8.300000
Mystery      8.442857
Romance      8.477778
Sci-Fi       8.509091
Thriller     8.436364
War          8.433333
Western      8.600000
Name: rating, dtype: float64

In [19]:
# Por último, podemos acceder a los primeros n elementos que queramos
ratings_by_genre.head(10)

genre
Action       8.573913
Adventure    8.514815
Animation    8.436364
Biography    8.537500
Comedy       8.425000
Crime        8.615000
Drama        8.545714
Family       8.533333
Fantasy      8.533333
Film-Noir    8.400000
Name: rating, dtype: float64